services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_PORT=5432
    volumes:
      - ./volumes/db/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
